### ISSUE TITLE
update for @use/@forward

### ISSUE THREAD

**Issue by jaxatto** [dvlden/differs#2]
Howdy, will you be updating this for @use/@forward instead of @import? 

I tried poking around with it in my own project but wasn't successful, just kept running into odd errors that I think stemmed from the latest Dart Sass...

Thank you for your work!

**Comment by dvlden** [comment]
Hello, 

This is a work in progress. I did not have much time to fiddle with it and to hopefully "finish it" for the actual use.

I'm glad that you want to try this out. I did not read about new updates and changes, but outside of this project, I am still using @import with Dart-Sass and I don't have any problems. So the problem may not be the `@use` and `@forward` _(whatever those might be, still not aware)_

I'll try to find some time within the next few days, give it an update and fix the issue. 

I appreciate the report! Thank you very much.

Regards,
Nenad Novakovic.

**Comment by jaxatto** [comment]
Of course! Thank you for the fast response. Your work is super appreciated, I definitely understand it's a work in progress. 

Your article from last year and this work is actually the only good material I can find on using maps like this, so I'm really excited to see it!

I really quick forked and updated to for using @use: https://github.com/jaxatto/differs-dash-latest

@import is not yet removed but will be deprecated sooner rather than later, I'm trying not to use it in my new project.

For reference, this is the message you get:
<img width="845" alt="Screen Shot 2020-01-20 at 7 33 13 PM" src="https://user-images.githubusercontent.com/6673768/72768162-0f038200-3bbc-11ea-834c-71833a76fa93.png">

Anyway, thank you again! Looking forward to your future work.

**Comment by jaxatto** [comment]
Hey! I figured it out today! Updated this repo: https://github.com/jaxatto/differs-modules 

That issue was being caused because it couldn't find the function. The error messaging just isn't robust enough to tell you why it thinks that value is invalid.

My solution probably isn't the best, and it's not as simple as @import for quick projects, but I think it makes a lot of sense. It's kinda like JS, or React imports, you don't import everything globally and use it wherever. I think of @use as the same thing. Just hard to keep track of at first!

Thanks again!

**Comment by dvlden** [comment]
Hey!

Yeah, I was reading docs yesterday night. The syntax is very similar to other modular languages, so it's simple to grasp. 

I like this one in particular... 

```
@use 'module' with (
  $color: #222,
  $radius: 4px
);
```

I think that Differs actually requires a rewrite because it should be modular as per this new implementation of Sass lang. Not a full rewrite tho, but it certainly needs to adopt the new changes.

I'll go through the documentation a couple more times to take it all in and then I'll play around to see what could come in handy for new rewrite.

Thank you for your time to figure this all out and to actually make it work again!

**Comment by jaxatto** [comment]
Awesome! The new features are very powerful, I'm sure you will do some awesome stuff with it. Thanks for your help!
